# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Logistics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test (in shell/)
        working-directory: shell
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job (shell/ contents)
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: shell

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Logistics'
          slot-name: 'Production'
          package: node-app/shell
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5806AE614B2E45338CEC3E1CCE1F2D48 }}